version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build:
      context: .
    command: uvicorn myapp.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  migration:
    build:
      context: ./migration_service
    environment:
      SQLALCHEMY_URL: postgresql+psycopg2://username:password@db/mydatabase
    depends_on:
      - db

volumes:
  db_data:
